version: 0.2
phases:
  install: 
    runtime-versions:
      golang: 1.13
    commands:
      - go get -u golang.org/x/lint/golint

  pre_build: 
    commands:
      - golint -set_exit_status
      - go test

  build:
    commands:
      - go build -o app

artifacts:
  files:
    - app
    - buildspec.yml



