version: 0.2
phases:
  install: 
    runtime-versions:
      golang: 1.18
    commands:
      - go get -u golang.org/x/lint/golint

      # install govulncheck to scan code
      - echo install govulncheck
      - go install golang.org/x/vuln/cmd/govulncheck@latest   
      - workdir=`pwd`
      - echo $workdir
      - ls -la       

  pre_build: 
    commands:
      - golint -set_exit_status
      - go test      

  build:
    commands:
      - go build -o app
      - echo gopath $GOPATH
      # Vulnerability detection using govulncheck
      - which govulncheck
      - echo trying to execute govulncheck on project
      - govulncheck -json ./... > golang-codebuild-aws-govulncheck-results.json
      - echo after govulncheck... 
      - pwd
      - ls -la      

artifacts:
  files:
    - app
    - buildspec.yml
    - golang-codebuild-aws-govulncheck-results.json



